freebsd_instance:
  image_family: freebsd-13-0

task:
  install_script: pkg install -y git bash base64 bats-core
  clone_script: |
    git clone https://github.com/borksh/bork bork
    git clone https://github.com/borksh/legacy legacy
  setup_script: |
    mv bork/test/helpers.sh legacy/test/
    rm -r bork/test/ bork/types/
    mv legacy/test/ bork/
    mv legacy/types/ bork/
    rm -r legacy/
  script: |
    cd bork
    /usr/local/bin/bash -c "bats --tap test"
